// Feature-vector parity: the TS port of `_build_per_frame_features` /
// `window_to_model_input` must match the Python reference bit-for-tol on a
// hand-built keypoint sequence. The fixture in __fixtures__/feature_parity.json
// is generated by running the actual Python `sign_dataset` helpers (see the
// dump in the workstream-C handoff). Tolerance is 1e-5 (fp32 vs JS doubles).
import { describe, it, expect } from 'vitest';
import {
  buildPerFrameFeatures,
  normaliseFrame,
  windowToModelInput,
  featureDim,
  NUM_KEYPOINTS,
} from '../../src/cv/pipeline/features';
import fixture from './__fixtures__/feature_parity.json';

const TOL = 1e-5;

/** Flatten a (T, 49, 2) nested array to the TS row-major buffer layout. */
function flattenKpts(kpts: number[][][]): { buf: Float32Array; T: number } {
  const T = kpts.length;
  const buf = new Float32Array(T * NUM_KEYPOINTS * 2);
  for (let t = 0; t < T; t++) {
    for (let i = 0; i < NUM_KEYPOINTS; i++) {
      buf[(t * NUM_KEYPOINTS + i) * 2] = kpts[t][i][0];
      buf[(t * NUM_KEYPOINTS + i) * 2 + 1] = kpts[t][i][1];
    }
  }
  return { buf, T };
}

function flattenVis(vis: number[][]): Float32Array {
  const T = vis.length;
  const buf = new Float32Array(T * NUM_KEYPOINTS);
  for (let t = 0; t < T; t++) for (let i = 0; i < NUM_KEYPOINTS; i++) buf[t * NUM_KEYPOINTS + i] = vis[t][i];
  return buf;
}

describe('feature vector parity (vs Python sign_dataset)', () => {
  const { buf: kpts, T } = flattenKpts(fixture.kpts as number[][][]);
  const vis = flattenVis(fixture.vis as number[][]);
  const W = fixture.W as number;
  const H = fixture.H as number;

  it('feature dim is 343 with all flags on', () => {
    expect(featureDim()).toBe(343);
  });

  it('normaliseFrame matches Python _normalise_frame on frame 0', () => {
    const out = new Float32Array(NUM_KEYPOINTS * 2);
    const kFrame = kpts.subarray(0, NUM_KEYPOINTS * 2);
    const vFrame = vis.subarray(0, NUM_KEYPOINTS);
    normaliseFrame(kFrame, vFrame, W, H, out);
    const ref = (fixture.norm0 as number[][]).flat();
    expect(out.length).toBe(ref.length);
    for (let i = 0; i < ref.length; i++) {
      expect(out[i]).toBeCloseTo(ref[i], 5);
    }
  });

  it('buildPerFrameFeatures matches Python (coords + vis + lag1 + lag2)', () => {
    const { feat, C } = buildPerFrameFeatures(kpts, vis, T, W, H);
    expect(C).toBe(343);
    const ref = fixture.feat as number[][];
    expect(ref.length).toBe(T);
    for (let t = 0; t < T; t++) {
      for (let i = 0; i < C; i++) {
        const got = feat[t * C + i];
        const want = ref[t][i];
        expect(Math.abs(got - want)).toBeLessThanOrEqual(TOL);
      }
    }
  });

  it('lag1 is zero on frame 0, lag2 is zero on frames 0 and 1', () => {
    const { feat, C } = buildPerFrameFeatures(kpts, vis, T, W, H);
    const coords = NUM_KEYPOINTS * 2; // 98
    const visLen = NUM_KEYPOINTS; // 49
    const lag1Off = coords + visLen; // 147
    const lag2Off = lag1Off + coords; // 245
    for (let i = 0; i < coords; i++) {
      expect(feat[0 * C + lag1Off + i]).toBe(0); // lag1 frame 0
      expect(feat[0 * C + lag2Off + i]).toBe(0); // lag2 frame 0
      expect(feat[1 * C + lag2Off + i]).toBe(0); // lag2 frame 1
    }
  });

  it('windowToModelInput subsamples (T>=max) with linspace+floor', () => {
    const { feat, C } = buildPerFrameFeatures(kpts, vis, T, W, H);
    const max = fixture.window_sub.max as number;
    const { feat: out, mask } = windowToModelInput(feat, T, C, max);
    const refFeat = (fixture.window_sub.feat as number[][]).flat();
    const refMask = fixture.window_sub.mask as number[];
    expect(Array.from(mask)).toEqual(refMask);
    for (let i = 0; i < refFeat.length; i++) {
      expect(Math.abs(out[i] - refFeat[i])).toBeLessThanOrEqual(TOL);
    }
  });

  it('subsample indices match numpy linspace().astype(int) at T=64,max=30', () => {
    // Build a (64, C) feature buffer whose first coord encodes the frame index,
    // so the subsampled output reveals which source rows were picked. The
    // expected indices come from numpy linspace(0,63,30).astype(int) (trunc).
    const C = featureDim();
    const Tn = 64;
    const feat = new Float32Array(Tn * C);
    for (let t = 0; t < Tn; t++) feat[t * C] = t;
    const expected = [
      0, 2, 4, 6, 8, 10, 13, 15, 17, 19, 21, 23, 26, 28, 30, 32, 34, 36, 39, 41,
      43, 45, 47, 49, 52, 54, 56, 58, 60, 63,
    ];
    const { feat: out, mask } = windowToModelInput(feat, Tn, C, 30);
    expect(Array.from(mask)).toEqual(new Array(30).fill(0));
    for (let k = 0; k < 30; k++) expect(out[k * C]).toBe(expected[k]);
  });

  it('windowToModelInput zero-pads tail (T<max) and masks padded steps', () => {
    const { feat, C } = buildPerFrameFeatures(kpts, vis, T, W, H);
    const max = fixture.window_pad.max as number;
    const { feat: out, mask } = windowToModelInput(feat, T, C, max);
    const refFeat = (fixture.window_pad.feat as number[][]).flat();
    const refMask = fixture.window_pad.mask as number[];
    expect(Array.from(mask)).toEqual(refMask);
    for (let i = 0; i < refFeat.length; i++) {
      expect(Math.abs(out[i] - refFeat[i])).toBeLessThanOrEqual(TOL);
    }
    // Padded steps (T..max) must be all-zero.
    for (let t = T; t < max; t++) {
      for (let i = 0; i < C; i++) expect(out[t * C + i]).toBe(0);
    }
  });
});
